# Generated by Django 4.0.1 on 2023-08-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoautorizacao',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.usoespaco'),
        ),
    ]
