# Generated by Django 4.0.1 on 2023-08-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.CharField(max_length=100)),
                ('descricao_condicao', models.TextField()),
                ('condicao_equipamento', models.CharField(choices=[('pessimo', 'Péssimo'), ('ruim', 'Ruim'), ('bom', 'Bom'), ('otimo', 'Ótimo'), ('excelente', 'Excelente')], max_length=9)),
                ('eletrica', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('hidraulica', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('serralheria', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('carpintaria', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('alvenaria', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('vidracaria', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('limpeza', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('pintura', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
                ('jardinagem', models.CharField(choices=[('muitobaixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('regular', 'Regular'), ('alta', 'Alta'), ('muitoalta', 'Muito Alta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('tamanho', models.FloatField()),
                ('condicao_equipamento', models.CharField(choices=[('pessimo', 'Péssimo'), ('ruim', 'Ruim'), ('bom', 'Bom'), ('otimo', 'Ótimo'), ('excelente', 'Excelente')], max_length=9)),
                ('rede_eletrica', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('rede_hidraulica', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('banheiro_vestiario', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('parques_jardins', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('arquibancada', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('cobertura', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('cercamento', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('grama_sintetica', models.CharField(choices=[('possui', 'Possui'), ('npossui', 'Não Possui')], max_length=7)),
                ('foto_aerea', models.ImageField(upload_to='')),
                ('fotos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EscolhaEquipamentoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'Segunda-Feira'), ('terca', 'Terça-Feira'), ('quarta', 'Quarta-Feira'), ('quinta', 'Quinta-Feira'), ('sexta', 'Sexta-Feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=7)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_idade', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando', 'Aguardando Resposta'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado')], max_length=10)),
                ('genero_biologico', models.CharField(choices=[('masc', 'Masculino'), ('fem', 'Feminino'), ('mis', 'Misto')], max_length=4)),
                ('estimativa_praticipantes', models.IntegerField()),
                ('data_expiracao', models.DateField(null=True)),
                ('publico_alvo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.publico')),
                ('tipo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tipoatividade')),
                ('tipo_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tipomodalidade')),
            ],
        ),
    ]
