# Generated by Django 4.0.1 on 2023-08-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usoespaco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escolhaequipamentohorario',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='escolhaequipamentohorario',
            name='uso_espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.usoespaco'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.bairro'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tipoequipamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_modalidade',
            field=models.ManyToManyField(to='equipamentos.TipoModalidade'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.cidade'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
        ),
    ]
